// atl.idl : IDL source for atl.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (atl.tlb) and marshalling code.
import "oaidl.idl";
import "atliface.idl";

[
	uuid(44EC0535-400F-11D0-9DCD-00A0C90391D3),
	version(1.0),
	helpstring("ATL 2.0 Type Library")
]
library ATLLib
{
	importlib("stdole32.tlb");

	[
		uuid(44EC053A-400F-11D0-9DCD-00A0C90391D3),
		helpstring("ATL Registrar Class")
	]
	coclass Registrar
	{
		[default] interface IRegistrar;
	};
};
